### ISSUE TITLE
gbk编码问题，导致运行错误，是不是要de掉这个bug，不然没法运行

### ISSUE THREAD

**Issue by CaptainEven** [yanwii/seq2seq#10]

**Comment by yanwii** [comment]
默认支持utf-8， 你先转一次就行，也欢迎pr

**Comment by yucongo** [comment]
Windows里 Python3：preprocessing.py里

   > with open(……, "r"')

的地方改成

   >with open(……, "r", encoding='utf8'’)

好像就可以搞定gbk编码错误
