### ISSUE TITLE
illegal hardware instruction

### ISSUE THREAD

**Issue by link-duan** [yanwii/seq2seq#11]
I followed the README.But I get this problem.
![image](https://user-images.githubusercontent.com/20787331/36834649-7fec33fe-1d6e-11e8-9695-ce3240e83eaf.png)

**Comment by yanwii** [comment]
Upgrade your numpy by `pip2 install -U numpy`

**Comment by link-duan** [comment]
Requirement already up-to-date: numpy in /usr/local/lib/python2.7/dist-packages

**Comment by link-duan** [comment]
doesn't work...

**Comment by yanwii** [comment]
try to run the script using python2.7

**Comment by link-duan** [comment]
oops...doesn't work.#_#...
![image](https://user-images.githubusercontent.com/20787331/36843989-becb2b30-1d8b-11e8-8274-197a6bf68e0a.png)

**Comment by yanwii** [comment]
take a look at  
https://stackoverflow.com/questions/45877158/illegal-instruction-error-when-building-tensorflow-from-source
