### ISSUE TITLE
input_size,output_size,hiden_size该如何设置，什么依据？

### ISSUE THREAD

**Issue by Sunwc0** [yanwii/seq2seq#17]
我的参数设置：
 self.input_size = 100
 self.output_size = 1200
 self.hidden_size = 1200
 self.max_length = 1200
训练时报错：数组越界错误，不知道是什么情况，忘不吝赐教，暂时没深入网络中去，想先跑个例子学习下，问题可能有点无脑
  File "/Users/sunwc/Documents/pythonproject/seq2seq-master/seq2seq.py", line 35, in forward
    embedded = self.embedding(word_inputs).view(seq_len, 1, -1)
RuntimeError: index out of range at /Users/soumith/code/builder/wheel/pytorch-src/aten/src/TH/generic/THTensorMath.cpp:352

**Comment by yanwii** [comment]
在这个模型中
input_size为encoder输入词典的大小
output_size为decoder输入词典的大小
hidden_size为每个lstm的隐藏层个数
max_length为encoder和decoder的最大句子长度

**Comment by Sunwc0** [comment]
好的多谢，大佬有没有个人网站，多向大佬学习

**Comment by Crescentz** [comment]
这个max_length 是个人设置的么 ，还是说语料库中 最长的句子长度。
