### ISSUE TITLE
RuntimeError这个是什么错误?

### ISSUE THREAD

**Issue by yeshoujquery** [yanwii/seq2seq#2]
RuntimeError: index out of range at /b/wheel/pytorch-src/torch/lib/TH/generic/THTensorMath.c:273

**Comment by yeshoujquery** [comment]
@yanwii input_size和output_size 这2个的值选取的是?

**Comment by yanwii** [comment]
这两个值取小了。
input_size   是问题字典的大小
output_size 是答案字典的大小

**Comment by yeshoujquery** [comment]
@yanwii question.txt和answer.txt 是这2个吗?

**Comment by yanwii** [comment]
enc.vocab 和dec.vocab  index的长度

**Comment by yeshoujquery** [comment]
@yanwii 我看到
`        str_to_vec = {}
        with open("./data/enc.vocab") as enc_vocab:
            for index,word in enumerate(enc_vocab.readlines()):
                str_to_vec[word.strip()] = index

        vec_to_str = {}
        with open("./data/dec.vocab") as dec_vocab:
            for index,word in enumerate(dec_vocab.readlines()):
                vec_to_str[index] = word.strip()

outstrs.append(vec_to_str.get(i, "Un"))
`
等于说是查询出来的数字用训练的词库替换出来 
如果二次训练怎么办?之前的词库还需要保留?如果保留就没办法提取了也会导致之前训练的会重复训练?
这个有点不理解 求解答

**Comment by yanwii** [comment]
如果你第二次训练有新词，那么肯定还是要对之前的内容重复训练的。不然模型就去拟合新的训练集，可能会忘记了以前学的知识，你得让它“复习”才行。
我建议你建立一个标准词库，有新词往里面添加就行，这样即使有新的词，前面的内容也不会乱。

**Comment by yeshoujquery** [comment]
@yanwii 这样的话每次训练都会把时间拉长 并且随着数据的增大 这个替换会越来越慢吧~ vec_to_str 会越来越大
`outstrs.append(vec_to_str.get(i, "Un"))`

**Comment by yanwii** [comment]
你有什么好点子？

**Comment by yeshoujquery** [comment]
@yanwii   tf那个是怎么实现的呢 我记得tf查出来之后也是一堆数字然后转化成文字的 ...

**Comment by yanwii** [comment]
都是一样的

**Comment by yeshoujquery** [comment]
@yanwii  那应该就不会有太大问题 google官方的 还是比较权威(哈哈) 你后面准备怎么优化?

**Comment by yeshoujquery** [comment]
@yanwii 上下文关联和 上一句问你什么加上就更好了

**Comment by yanwii** [comment]
上下文是热点研究，中文不好对付。

**Comment by skarl-api** [comment]
@yanwii 有啥好的标准库么或者qa材料发一些 多谢
