### ISSUE TITLE
RuntimeError: cuda runtime error (59) : device-side assert triggered 

### ISSUE THREAD

**Issue by liutianling** [yanwii/seq2seq#20]
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/torch/lib/THC/generic/THCTensorCopy.c:18
出现这个问题是我改了代码
                    #words = jieba.lcut(sentence)
                    words = [word for word in sent]
改动之后没有使用结巴分词，直接用的字符做的输入，这样训练的时候为什么会有上面的错误，谢谢

另外有点问题想请教下：
１　你的代码中对原始数据也就是问答数据进行jieba分词处理，最后是直接对词进行的编码然后输入，我想问的是这种分词与否是否会对结果有影响，为什么？
２　中文数据中的标点符号需要去除吗？

**Comment by yanwii** [comment]
请问您对数据集做了修改吗？我跑demo是没有问题的，改成字符级的数据也是没问题。
1.模型内部进行了embedding的处理，如果您想获得更好的结果，建议使用预训练的词向量或字向量。理论上来说，分词的结果和词向量会影响模型的结果。
2.是否去除标点符号和停词完全取决与您的应用场景。

**Comment by liutianling** [comment]
@yanwii 非常感谢你的答复，你的demo完全没有问题，字符级的数据也没有问题
你给的数据只有一个问答，我在后面加了一个问答也没有问题
但是，遇到这样的问答就会出现我上面说的问题，这是我加的问答
Q:我还喜欢她，怎么办？
A:我帮你告诉他，打电话还是发短信？

多次测试，我好像找到了问题，但是对你代码中的参数的具体意义不是很清楚，
        self.input_size = 14
        self.output_size = 15
        self.hidden_size = 100
        self.max_length = 15

就是说你的q或者ａ字符的长度一旦达到一定长度的时候，代码就无法处理了
因为代码中给字符前面加上了这几个字符
__PAD__
__GO__
__EOS__
__UNK__
所以你的q或者a的字符长度达到１２的时候，输入肯定是大于你设定的１４或者１５了，你这里两个size和一个max_length我不太理解具体是什么含义，
谢谢！

**Comment by yanwii** [comment]
input_size和output_size分别对应encoder和decoder的字典大小。具体来说，如果使用词级的训练数据，就是词去重后的个数，如果字级则是字去重后的个数。max_length则是表示每个句子的最大长度。这个项目比较久远了，没有通过数据集自动设置参数，需要手动设置。

**Comment by liutianling** [comment]
@yanwii 谢谢，明白了，max_length获取一下就OK了，谢谢你！
