### ISSUE TITLE
RuntimeError: Assertion `cur_target >= 0 && cur_target < n_classes' failed

### ISSUE THREAD

**Issue by yeshoujquery** [yanwii/seq2seq#4]
RuntimeError: Assertion `cur_target >= 0 && cur_target < n_classes' failed.  at /b/wheel/pytorch-src/torch/lib/THNN/generic/ClassNLLCriterion.c:45

这个是什么错误呢？训练到 epoch: 16800 之后出现的错误

**Comment by yanwii** [comment]
output_size 小了

**Comment by yeshoujquery** [comment]
@yanwii 嗯 后来发现了 现在这个项目你那有什么更新吗?

**Comment by yeshoujquery** [comment]
@yanwii 我看现在没有会话Id, 如果加上会话Id 是否可以更好一点的上下文?

**Comment by yanwii** [comment]
是的。加上id还能做多轮对话。

**Comment by yeshoujquery** [comment]
@yanwii 为什么总提醒 No model! 但是明明params.pkl 是存在的啊~ 好奇怪啊

**Comment by yanwii** [comment]
我看了一下。如果你修改了模型的参数，加载模型的时候就会报错，所以就回显示no model！

**Comment by yeshoujquery** [comment]
@yanwii 那这个问题如何解决呢? 不过我发现 现在我训练的数据多了 反而变得更傻了.

**Comment by yanwii** [comment]
微信 q403497193

**Comment by yeshoujquery** [comment]
搜索不到 哈哈

**Comment by yeshoujquery** [comment]
params.pkl 如何初始化一个空的呢 训练了300000万次但是结果傻掉了

**Comment by haluowan** [comment]
@yeshoujquery ，我也出现了这个错误，手动修改output_size 后，出现如下错误：
RuntimeError: index out of range at c:\new-builder_3\win-wheel\pytorch\aten\src\th\generic/THTensorMath.cpp:352
怎么解决呢？
