### ISSUE TITLE
Traceback (most recent call last):   File "seq2seq.py", line 441, in <module>     seq.train()   File "seq2seq.py", line 211, in train     inputs, targets = self.next(1, shuffle=False)   File "seq2seq.py", line 193, in next     inputs = Variable(torch.LongTensor(inputs)).transpose(1, 0).contiguous() RuntimeError: given sequence has an invalid size of dimension 2: 0

### ISSUE THREAD

**Issue by skarl-api** [yanwii/seq2seq#6]
这个错误是什么意思呢？
Traceback (most recent call last):
  File "seq2seq.py", line 441, in <module>
    seq.train()
  File "seq2seq.py", line 211, in train
    inputs, targets = self.next(1, shuffle=False)
  File "seq2seq.py", line 193, in next
    inputs = Variable(torch.LongTensor(inputs)).transpose(1, 0).contiguous()
RuntimeError: given sequence has an invalid size of dimension 2: 0

**Comment by yanwii** [comment]
inputs是空的

**Comment by skarl-api** [comment]
@yanwii  恍然大悟
