### ISSUE TITLE
如何加入自己的訓練資料?

### ISSUE THREAD

**Issue by Truth1987** [yanwii/seq2seq#8]
您好，想請問如何加入自己的對話訓練資料?

謝謝。

**Comment by yanwii** [comment]
data目录下有question.txt和answer.txt文件，分别是问和答，一一对应，然后运行python3 preprocessing.py 进行预处理即可

**Comment by Truth1987** [comment]
您好，那預處理之後，需要 train嗎?

**Comment by yanwii** [comment]
可以参考[用法](https://github.com/yanwii/seq2seq#%E7%94%A8%E6%B3%95)  
 python3 seq2seq.py retrain 重新训练

**Comment by Truth1987** [comment]
謝謝您的回應
我試試看
