### ISSUE TITLE
cuda runtime error

### ISSUE THREAD

**Issue by Truth1987** [yanwii/seq2seq#9]
>, TensorInfo<long, IndexType>, int, int, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [0,0,0], thread: [91,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/torch/lib/THC/THCTensorIndex.cu:279: void indexSelectSmallIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [0,0,0], thread: [92,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/torch/lib/THC/THCTensorIndex.cu:279: void indexSelectSmallIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [0,0,0], thread: [93,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/torch/lib/THC/THCTensorIndex.cu:279: void indexSelectSmallIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [0,0,0], thread: [94,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/torch/lib/THC/THCTensorIndex.cu:279: void indexSelectSmallIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [0,0,0], thread: [95,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCTensorCopy.c line=21 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "seq2seq.py", line 453, in <module>
    seq.train()
  File "seq2seq.py", line 227, in train
    loss, logits = self.step(inputs, targets, self.max_length)
  File "seq2seq.py", line 259, in step
    decoder_input = decoder_input.cuda()
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/variable.py", line 298, in cuda
    return CudaTransfer.apply(self, device, async)
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/_functions/tensor.py", line 201, in forward
    return i.cuda(async=async)
  File "/usr/local/lib/python3.5/dist-packages/torch/_utils.py", line 69, in _cuda
    return new_type(self.size()).copy_(self, async)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/torch/lib/THC/generic/THCTensorCopy.c:21

**Comment by yanwii** [comment]
Did you run the demo or on your own datasets?

**Comment by Truth1987** [comment]
YES, it;s my own data.
It seems work fine when run on your data.

**Comment by yanwii** [comment]
Check your  `decoder_input` if there any minuses in it.

**Comment by Truth1987** [comment]
在Data底下沒看到 decoder_input 這個檔案
answer.txt    dec.vec    enc.segement  enc.vocab     supplementvocab.txt
dec.segement  dec.vocab  enc.vec       question.txt

我該去哪兒找這個檔案?

**Comment by yanwii** [comment]
dec.vec and enc.vec

**Comment by Truth1987** [comment]
這是我一部分的資料，請參考。

[dec.vec.txt](https://github.com/yanwii/seq2seq/files/1660666/dec.vec.txt)
[enc.vec.txt](https://github.com/yanwii/seq2seq/files/1660667/enc.vec.txt)

**Comment by yanwii** [comment]
dec.vec.text 中有一些空行 也许就是错误所在

**Comment by Truth1987** [comment]
[dec.vec.txt](https://github.com/yanwii/seq2seq/files/1662294/dec.vec.txt)
[enc.vec.txt](https://github.com/yanwii/seq2seq/files/1662295/enc.vec.txt)

我把空格拿掉了，執行 `python3 seq2seq.py retrain`
情況沒有改變

**Comment by yanwii** [comment]
检查一下您的decode中的最大下标是否大于output_size这个参数

**Comment by xingzhoupy** [comment]
你解决了吗?和你一样的错误

**Comment by xibinyue** [comment]
应该是标点的编码问题，希望楼主关注一下

**Comment by xibinyue** [comment]
change the max length

**Comment by Kiteflyingee** [comment]
[可以参考issue#2 [https://github.com/yanwii/seq2seq/issues/2](url)

**Comment by yanwii** [comment]
refer to #2
